### ISSUE TITLE
Add mypy static analysis

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-libs#14]
A mypy check should be added to CI.

- [ ] Make codebase pass mypy check
- [ ] Add mypy check to travis script

**Comment by pcppcp** [comment]
don't forget to call `mypy` with  `--ignore-missing-imports` options, otherwise we won't make it :)

**Comment by LefterisJP** [comment]
Hmmm is this something we need to focus on? Let's do the extra CI checks (also in Raiden) only when we really need them. CI is gonna get really slow if we overdo it at this point.

**Comment by palango** [comment]
Not really, but good to have an issue anyways. Shouldn't be so hard to fix either.
