### ISSUE TITLE
Add gevent based matrix client

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-libs#2]

**Comment by palango** [comment]
This should also include tools to decode, verify and send messages according to the message spec in https://github.com/raiden-network/spec/pull/38

**Comment by andrevmatos** [comment]
My implementation: https://github.com/andrevmatos/matrix-test/blob/master/gmatrixclient.py
The encode/decode part, though, is in [main.py](https://github.com/andrevmatos/matrix-test/blob/master/main.py), as it's part of the logic of the app.

**Comment by palango** [comment]
This was fixed by #26

**Comment by pcppcp** [comment]
I kinda like Andre's implementation, as it replaces thread spawn with gevent calls. But since the `matrix-client` guys have PR for including gevent pending, it might be not necessary.

**Comment by andrevmatos** [comment]
For reference, @ulope and mine's implementation was merged in #39 
Main selling point: inheritance allows easy implementation of missing methods, with transparent access to direct API (http), internal methods and attributes. About the matrix official implementation, there seems to be no further progress in https://github.com/matrix-org/matrix-python-sdk/issues/127 and related PRs, so I think it's better for us to extend over the stable codebase keeping compatibility. We may even contribute some of the methods upstream in the near future.
