### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden-libs#87]
We need to cut a release at some point so Raiden can point to a pinned version in its requirements.txt.

See also: raiden-network/raiden#1381 and raiden-network/raiden#1373

**Comment by pcppcp** [comment]
The library is ready to be released - just do `py setup.py sdist upload`.

But I'd wait with the actual upload until we actually release Raiden (plus `raiden-contracts` - it'll be done in one bunch).

So I propose we close this one and track libs, contracts upload + requirements update in one issue in Raiden repo.
